apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-nam
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  source:
    repoURL: https://github.com/sk880624/gh-first-action.git
    targetRevision: master
    path: env/stg/app01-nam
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true